-- +goose Up

CREATE SCHEMA IF NOT EXISTS lk;

CREATE TABLE IF NOT EXISTS lk.orders (
      id bigint generated always as identity primary key,
      weight int not null,
      region int not null check ( region > 0 ),
      cost bigint not null,
      delivery_hours text[] not null,
      complete_at timestamp,
      created_at timestamp default (now() at time zone 'utc'),
      deleted_at timestamp
);


DROP TYPE IF EXISTS lk.courier_type;
CREATE TYPE lk.courier_type AS ENUM
(
    'UNKNOWN',
    'FOOT',
    'BICYCLE',
    'CAR'
);

CREATE TABLE IF NOT EXISTS lk.couriers
(
    id bigint generated always as identity primary key,
    courier_type lk.courier_type not null,
    regions integer[] constraint check_positive_regions check (0 < all(regions)),
    working_hours text[],
    created_at timestamp default (now() at time zone 'utc'),
    deleted_at timestamp
);

CREATE INDEX IF NOT EXISTS idx_orders_complete_at ON lk.orders (complete_at);


CREATE TABLE IF NOT EXISTS  lk.couriers_orders (
   id bigint generated always as identity primary key,
   order_id bigint references lk.orders (id) on delete cascade not null,
   courier_id bigint references lk.couriers (id) on delete cascade not null
);

CREATE TABLE IF NOT EXISTS lk.assignments_dates (
    id  int generated always as identity primary key,
    date date not null,
    version int generated by default as identity not null,
    unique (version, date)
);


CREATE TABLE IF NOT EXISTS lk.assignments (
    id  bigint generated always as identity primary key,
    date_id int references lk.assignments_dates (id) on delete cascade not null,
    courier_id bigint references lk.couriers (id) on delete cascade not null,
    group_order_ids bigint[]
);


CREATE TABLE IF NOT EXISTS lk.assign_lim (
      id int generated always as identity primary key not null,
      courier_type lk.courier_type not null,
      lim jsonb not null
);


-- +goose Down
DROP SCHEMA IF EXISTS lk CASCADE;
