apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lavka-app.fullname" . }}-config
  labels:
    {{- include "lavka-app.labels" . | nindent 4 }}
  namespace: {{ include "lavka-app.namespace" . }}
data:
  HTTP_HOST:  {{ .Values.configData.http.host }}
  HTTP_PORT: {{ .Values.configData.http.port | quote }}
  HTTP_READ: {{ .Values.configData.http.read | quote }}
  DB_HOST: {{ .Values.configData.db.host }}
  DB_PORT: {{ .Values.configData.db.port | quote }}
  DB_USER: {{ .Values.configData.db.user }}
  DB_NAME: {{ .Values.configData.db.name }}
