apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lavka-app.fullname" . }}-secret
  labels:
    {{- include "lavka-app.labels" . | nindent 4 }}
  namespace: {{ include "lavka-app.namespace" . }}
type: Opaque
stringData:
  db-pass: {{ .Values.db.secret.pass}}