apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.app.priority.className }}
  namespace: {{ include "lavka-app.namespace" . }}
value: {{ .Values.app.priority.value }}
globalDefault: false
description: "app priority class"
preemptionPolicy: PreemptLowerPriority