apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app.pv.volumeName }}
  namespace: {{ include "lavka-app.namespace" . }}
spec:
  capacity:
    storage: {{ .Values.app.persistence.claim }}
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    - {{ .Values.app.pv.accessMode | quote }}
  persistentVolumeReclaimPolicy: {{ .Values.app.pv.reclaimPolicy }}
  volumeMode: {{ .Values.app.pv.volumeMode }}
  local:
    path: {{ .Values.app.pv.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
              values: [ ]

