{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lavka-app.serviceAccountName" . }}-binding-cluster
  namespace: {{ include "lavka-app.namespace" . }}
  labels:
    {{- include "lavka-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: {{ .Values.serviceAccount.clusterRole }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "lavka-app.serviceAccountName" . }}
{{- end }}