{{- if .Values.serviceAccount.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "lavka-app.serviceAccountName" . }}-{{.Values.serviceAccount.role}}
  namespace: {{ include "lavka-app.namespace" . }}
  labels:
    {{- include "lavka-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods", "pods/log"]
    verbs: ["get", "list"]
{{- end }}