{{- if .Values.serviceAccount.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "lavka-app.serviceAccountName" . }}-binding
  namespace: {{ include "lavka-app.namespace" . }}
  labels:
   {{- include "lavka-app.labels" . | nindent 4 }}
 {{- with .Values.serviceAccount.annotations }}
  annotations:
   {{- toYaml . | nindent 4 }}
 {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lavka-app.serviceAccountName" . }}
    namespace: {{ include "lavka-app.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lavka-app.serviceAccountName" . }}-{{.Values.serviceAccount.role}}
{{- end }}
