apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db.name" . }}-config
  labels:
    {{- include "db.labels" . | nindent 4 }}
  namespace: {{ include "lavka-app.namespace" . }}
{{/*  annotations:*/}}
{{/*    "helm.sh/hook": pre-install,pre-upgrade*/}}
{{/*    "helm.sh/hook-weight": "-5"*/}}
{{/*    "helm.sh/hook-delete-policy": before-hook-creation*/}}
data:
  POSTGRES_DB: {{ .Values.configData.db.name }}
  POSTGRES_USER: {{ .Values.configData.db.user }}
  PGDATA: {{ .Values.configData.db.data }}

