apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db.name" . }}-migrate-config
  labels:
    {{- include "db.labels" . | nindent 4 }}
  namespace: {{ include "lavka-app.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  migrate.sh: |-
    #!/bin/bash
    set -e

    DSN="host={{ .Values.configData.db.host }} user={{ .Values.configData.db.user }} password=$POSTGRES_PASSWORD dbname={{ .Values.configData.db.name }} sslmode=disable"
    goose postgres "$DSN" up
    goose postgres "$DSN" status
