apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.db.priority.className }}
  namespace: {{ include "lavka-app.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation
value: {{ .Values.db.priority.value }}
globalDefault: false
description: "db priority class"
preemptionPolicy: PreemptLowerPriority