apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.name" . }}-secret
  labels:
    {{- include "db.labels" . | nindent 4 }}
  namespace: {{ include "lavka-app.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  postgresql-password: {{.Values.db.secret.pass}}