// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AssignLim        string
	Assignments      string
	AssignmentsDates string
	Couriers         string
	CouriersOrders   string
	Orders           string
}{
	AssignLim:        "assign_lim",
	Assignments:      "assignments",
	AssignmentsDates: "assignments_dates",
	Couriers:         "couriers",
	CouriersOrders:   "couriers_orders",
	Orders:           "orders",
}
